name: eShopOnWeb Build and Test

on: 
  [push, workflow_dispatch]

env:
  RESOURCE-GROUP: az400-test-rg-harsh
  LOCATION: westus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: KMLDevSubscription
  WEBAPP-NAME: eshoponweb-webapp-hshu

jobs:
  # Build, test and publish .NET web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v4

      # prepare runner for desired .NET version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      # Build/Test/Publish the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      # upload the published website code artifacts
      - name: Upload artifact for deployment job (.NET app)
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      # upload the bicep template (just the file)
      - name: Upload artifact for deployment job (Bicep template)
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: infra/webapp.bicep

  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      # Download the publish files created in previous job
      - name: Download artifact from build job (.NET app)
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      # Download the bicep templates from previous job
      - name: Download artifact from build job (Bicep template)
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      # Debug step: list contents to confirm template path
      - name: List downloaded files
        run: ls -R bicep-template

      # Login in your Azure subscription using a service principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: Deploy infra with Bicep
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep   # <-- corrected path
          parameters: 'webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}'
          failOnStdErr: false   

      # Publish website to Azure App Service using CLI
      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            az webapp deploy \
              --name ${{ env.WEBAPP-NAME }} \
              --resource-group ${{ env.RESOURCE-GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
